apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mutants
  name: mutantops-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutantops-operator
  template:
    metadata:
      labels:
        app: mutantops-operator
    spec:
      serviceAccountName: mutantops-operator
      containers:
      - name: mutantops-operator
        image: your-registry/mutantops:v1
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "mutantops-operator"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mutantops-operator
  namespace: mutants
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mutantops-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neiam.org
  resources:
  - mutantdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mutantops-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mutantops-operator
subjects:
  - kind: ServiceAccount
    name: mutantops-operator
    namespace: mutants